@startuml
package presentation
{
    +class Main
    {
        +main(args : String[]) : void
    }
}

package domain
{
    package stylecheck
    {
        +class StyleRevisionClassVisitor
        {
            -revisers : List<ClassStyleReviser>
            -revisionPrinter : StyleRevisionPrinter

            +StyleRevisionClassVisitor()

            +addStyleReviser(reviser : ClassStyleReviser) : void
            +removeStyleReviser(reviser : ClassStyleReviser) : void
            +setRevisionPrinter(printer : StyleRevisionPrinter) : void
            +visitField(…) : FieldVisitor
            +visitMethod(…) : MethodVisitor
            +visitInnerClass(…) : void
            +visitEnd() : void
            -getLocalClassName(internalName : String) : String
        }
        note left of StyleRevisionClassVisitor::visitEnd
          get all the revisions from each reviser
          and print using the revisionPrinter
        end note

        ~abstract class ClassStyleReviser
        {
            -revisions : List<StyleRevision>

            ~{abstract} checkClassName(name : String) : boolean
            ~{abstract} checkVariableOrMethodName(name : String) : boolean
            ~{abstract} checkStaticConstantName(name : String) : boolean
            ~{final} saveRevision(revision : StyleRevision) : void
            ~{final} getRevisions() : List<StyleRevision>
            ~{final} validateNameInput(name : String) : void
        }

        +class NamingConventionStyleReviser
        {
            ~checkClassName(name : String) : boolean
            ~checkVariableOrMethodName(name : String) : boolean
            ~checkStaticConstantName(name : String) : boolean
        }

        +class ReadableNamingStyleReviser
        {
            ~checkClassName(name : String) : boolean
            ~checkVariableOrMethodName(name : String) : boolean
            ~checkStaticConstantName(name : String) : boolean
            -checkReadability(name : String) : boolean
        }

        ~class StyleRevision
        {
            -issueLocation : String
            -issueDetails : String
            -suggestedFix : String

            ~getIssueLocation() : String
            ~getIssueDetails() : String
            ~getSuggestedFix() : String
        }

        ~class StyleRevision::Builder <<static>>
        {
            ~withIssueLocation(issueLocation : String) : StyleRevision::Builder
            ~withIssueType(issueType : String) : StyleRevision::Builder
            ~withSuggestedFix(suggestedFix : String) : StyleRevision::Builder
            ~build() : StyleRevision
        }

        ~abstract class StyleRevisionPrinter
        {
            -output : OutputStream

            ~StyleRevisionPrinter(output : OutputStream)
            ~{abstract} print(revision : StyleRevision, to : OutputStream) : void
        }

        ~class BasicStyleRevisionPrinter
        {
            ~print(revision : StyleRevision, to : OutputStream) : void
        }
    }
}

package datasource
{

}

package asm
{
    +abstract class ClassVisitor
    {
    }
}

StyleRevisionClassVisitor --|> ClassVisitor
StyleRevisionClassVisitor --> ClassStyleReviser
StyleRevisionClassVisitor --> StyleRevisionPrinter
NamingConventionStyleReviser --|> ClassStyleReviser
ReadableNamingStyleReviser --|> ClassStyleReviser
StyleRevision +-- StyleRevision::Builder
ClassStyleReviser --> StyleRevision
StyleRevisionPrinter ..> StyleRevision
BasicStyleRevisionPrinter --|> StyleRevisionPrinter
@enduml