@startuml
package presentation
{
    +class Main
    {
        +main(args : String[]) : void
    }
}

package domain
{
    package stylecheck
    {
        +class StyleRevisionClassVisitor
        {
            -revisers : List<ClassStyleReviser>
            -revisionPrinter : StyleRevisionPrinter

            +StyleRevisionClassVisitor()

            +addStyleReviser(reviser : ClassStyleReviser) : void
            +removeStyleReviser(reviser : ClassStyleReviser) : void
            +setRevisionPrinter(printer : StyleRevisionPrinter) : void
            +visitField(…) : FieldVisitor
            +visitMethod(…) : MethodVisitor
            +visitInnerClass(…) : void
            +visitEnd() : void
            -getLocalClassName(internalName : String) : String
        }
        note left of StyleRevisionClassVisitor::visitEnd
          get all the revisions from each reviser
          and print using the revisionPrinter
        end note

        ~abstract class ClassStyleReviser
        {
            -revisions : List<StyleRevision>

            ~{final} checkClassName(name : String) : boolean
            ~{final} checkVariableOrMethodName(name : String) : boolean
            ~{final} checkStaticConstantName(name : String) : boolean
            ~{abstract} checkClassNameInternal(name : String, revisionBuilder : StyleRevision::Builder) : boolean
            ~{abstract} checkVariableOrMethodNameInternal(name : String, revisionBuilder : StyleRevision::Builder) : boolean
            ~{abstract} checkStaticConstantNameInternal(name : String, revisionBuilder : StyleRevision::Builder) : boolean
            ~{final} saveRevision(revision : StyleRevision) : void
            ~{final} getRevisions() : List<StyleRevision>
            -validateNameInput(name : String) : void
        }

        +class NamingConventionStyleReviser
        {
            ~checkClassNameInternal(name : String, revisionBuilder : StyleRevision::Builder) : boolean
            ~checkVariableOrMethodNameInternal(name : String, revisionBuilder : StyleRevision::Builder) : boolean
            ~checkStaticConstantNameInternal(name : String, revisionBuilder : StyleRevision::Builder) : boolean
        }

        +class ReadableNamingStyleReviser
        {
            ~checkClassNameInternal(name : String, revisionBuilder : StyleRevision::Builder) : boolean
            ~checkVariableOrMethodNameInternal(name : String, revisionBuilder : StyleRevision::Builder) : boolean
            ~checkStaticConstantNameInternal(name : String, revisionBuilder : StyleRevision::Builder) : boolean
            -checkReadability(name : String, revisionBuilder : StyleRevision::Builder) : boolean
            -isReadable(name : String) : boolean
        }

        ~class StyleRevision
        {
            -originalName : String
            -issueLocation : String
            -issueDetails : String
            -suggestedFix : String

            ~getOriginalName() : String
            ~getIssueLocation() : String
            ~getIssueDetails() : String
            ~getSuggestedFix() : String
        }

        ~class StyleRevision::Builder <<static>>
        {
            ~withOriginalName(originalName : String) : StyleRevision::Builder
            ~withIssueLocation(issueLocation : String) : StyleRevision::Builder
            ~withIssueType(issueType : String) : StyleRevision::Builder
            ~withSuggestedFix(suggestedFix : String) : StyleRevision::Builder
            ~build() : StyleRevision
        }

        ~abstract class StyleRevisionPrinter
        {
            -output : OutputStream

            ~StyleRevisionPrinter(output : OutputStream)
            ~{final} print(data : String) : void
            ~{abstract} print(revision : StyleRevision, to : OutputStream) : void
        }

        ~class BasicStyleRevisionPrinter
        {
            ~print(revision : StyleRevision, to : OutputStream) : void
        }
    }
}

package datasource
{

}

package asm
{
    +abstract class ClassVisitor
    {
    }
}

StyleRevisionClassVisitor --|> ClassVisitor
StyleRevisionClassVisitor --> ClassStyleReviser
StyleRevisionClassVisitor --> StyleRevisionPrinter
NamingConventionStyleReviser --|> ClassStyleReviser
ReadableNamingStyleReviser --|> ClassStyleReviser
StyleRevision +-- StyleRevision::Builder
ClassStyleReviser --> StyleRevision
NamingConventionStyleReviser ..> StyleRevision
ReadableNamingStyleReviser ..> StyleRevision
ClassStyleReviser ..> StyleRevision::Builder
NamingConventionStyleReviser ..> StyleRevision::Builder
ReadableNamingStyleReviser ..> StyleRevision::Builder
StyleRevisionPrinter ..> StyleRevision
BasicStyleRevisionPrinter -l-|> StyleRevisionPrinter
@enduml