@startuml
package presentation
{
    +class Main
    {
        +main(args : String[]) : void
    }
}

package domain
{
    package stylecheck
    {
        +class ClassStyleRevisionManager
        {
            -revisers : List<ClassStyleReviser>
            -revisionPrinter : StyleRevisionPrinter

            +ClassStyleRevisionManager(output : OutputStream)

            +addStyleReviser(reviser : ClassStyleReviser) : void
            +removeStyleReviser(reviser : ClassStyleReviser) : void
            +revise(classNode : ClassNode) : void
            -reviseClassName(name : String) : void
            -reviseField(field : FieldNode) : void
            -reviseMethod(method : MethodNode) : void
            -reviseInnerClass(innerClass : innerClassNode) : void
            -printRevisions() : void
            -getLocalClassName(internalName : String) : String
        }

        ~abstract class ClassStyleReviser
        {
            -revisions : List<StyleRevision>

            ~{final} checkClassName(name : String) : boolean
            ~{final} checkVariableOrMethodName(name : String) : boolean
            ~{final} checkStaticConstantName(name : String) : boolean
            ~{abstract} checkClassNameInternal(name : String, revisionBuilder : StyleRevision::Builder) : boolean
            ~{abstract} checkVariableOrMethodNameInternal(name : String, revisionBuilder : StyleRevision::Builder) : boolean
            ~{abstract} checkStaticConstantNameInternal(name : String, revisionBuilder : StyleRevision::Builder) : boolean
            ~{final} saveRevision(revision : StyleRevision) : void
            ~{final} getRevisions() : List<StyleRevision>
            -validateNameInput(name : String) : void
        }

        +class NamingConventionStyleReviser
        {
            ~checkClassNameInternal(name : String, revisionBuilder : StyleRevision::Builder) : boolean
            ~checkVariableOrMethodNameInternal(name : String, revisionBuilder : StyleRevision::Builder) : boolean
            ~checkStaticConstantNameInternal(name : String, revisionBuilder : StyleRevision::Builder) : boolean
        }

        +class ReadableNamingStyleReviser
        {
            ~checkClassNameInternal(name : String, revisionBuilder : StyleRevision::Builder) : boolean
            ~checkVariableOrMethodNameInternal(name : String, revisionBuilder : StyleRevision::Builder) : boolean
            ~checkStaticConstantNameInternal(name : String, revisionBuilder : StyleRevision::Builder) : boolean
            -checkReadability(name : String, revisionBuilder : StyleRevision::Builder) : boolean
            -isReadable(name : String) : boolean
        }

        ~class StyleRevision
        {
            -originalName : String
            -issueLocation : String
            -issueDetails : String
            -suggestedFix : String

            ~getOriginalName() : String
            ~getIssueLocation() : String
            ~getIssueDetails() : String
            ~getSuggestedFix() : String
        }

        ~class StyleRevision::Builder <<static>>
        {
            ~withOriginalName(originalName : String) : StyleRevision::Builder
            ~withIssueLocation(issueLocation : String) : StyleRevision::Builder
            ~withIssueType(issueType : String) : StyleRevision::Builder
            ~withSuggestedFix(suggestedFix : String) : StyleRevision::Builder
            ~build() : StyleRevision
        }

        ~abstract class StyleRevisionPrinter
        {
            -output : OutputStream

            ~StyleRevisionPrinter(output : OutputStream)
            ~{final} print(data : String) : void
            ~{abstract} print(revision : StyleRevision, to : OutputStream) : void
        }

        +class BasicStyleRevisionPrinter
        {
            ~print(revision : StyleRevision, to : OutputStream) : void
        }
    }

    package classdiagram
    {
        +class PlantUMLGenerator
        {
            -classNodes : List<ClassNode>

            +generateClassDiagram(rootDirectoryPath : String, output : OutputStream) : void
            +generateClass(node : ClassNode) : String
            -generateField(field : FieldNode) : String
            -generateMethod(field : methodNode) : String
            -generateInnerClass(innerClass : innerClassNode) : String
        }
    }
}

package datasource
{

}

package asm
{
    +class ClassNode
    {
    }

    +class FieldNode
    {
    }

    +class MethodNode
    {
    }

    +class InnerClassNode
    {
    }
}

Main ..> ClassStyleRevisionManager
Main ..> asm

ClassStyleRevisionManager --> ClassStyleReviser
ClassStyleRevisionManager --> StyleRevisionPrinter
ClassStyleRevisionManager ..> ClassNode
ClassStyleRevisionManager ..> FieldNode
ClassStyleRevisionManager ..> MethodNode
ClassStyleRevisionManager ..> InnerClassNode
NamingConventionStyleReviser --|> ClassStyleReviser
ReadableNamingStyleReviser --|> ClassStyleReviser
StyleRevision +-- StyleRevision::Builder
ClassStyleReviser --> StyleRevision
NamingConventionStyleReviser ..> StyleRevision
ReadableNamingStyleReviser ..> StyleRevision
ClassStyleReviser ..> StyleRevision::Builder
NamingConventionStyleReviser ..> StyleRevision::Builder
ReadableNamingStyleReviser ..> StyleRevision::Builder
StyleRevisionPrinter ..> StyleRevision
BasicStyleRevisionPrinter -l-|> StyleRevisionPrinter
@enduml